# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 224b6db34410ebe7d4830370babfe71f3608dd219a47083b795816a76abd678b099a8cf51406e3c0af1e0fd0b71c084ce3da62e55e8f969cd082583da15a9f12

test:
  secret_key_base: 57f296aebdd889b0ab2010ceed625e4b37a3230b7a1d1dc186c29ba9a6013eb675df640d4c9280f01d15bb6b251f2d02026985b2e3ed1267b5d056a10f5f4981

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
